import { getCriminals } from "./criminals/criminalDataProvider.js";
import { criminalList } from "./criminals/CriminalList.js";
import { criminalListButton } from "./criminals/CriminalListButton.js";
import { ConvictionSelect } from "./convictions/ConvictionsSelect.js";
import { getConvictions } from "./convictions/convictionsDataProvider.js";
import { NoteForm } from "./notes/NoteForm.js";
import { witnessListButton } from "./witnesses/WitnessListButton.js";
import { getWitnesses } from "./witnesses/witnessDataProvider.js";
import { getNotes } from "./notes/noteDataProvider.js";
import { noteListButton } from "./notes/NoteListButton.js";
import { witnessListEventListener } from "./witnesses/WitnessList.js";
import { OfficerSelect } from "./officers/OfficerSelect.js";
import { getOfficers } from "./officers/officerDataProvider.js";

NoteForm();
noteListButton();
getNotes();
getWitnesses().then(witnessListButton).then(witnessListEventListener);
getCriminals().then(criminalList).then(criminalListButton);
getConvictions().then(ConvictionSelect);
getOfficers().then(OfficerSelect);