import { getCriminals } from "./criminals/criminalDataProvider.js";
import { criminalList } from "./criminals/CriminalList.js";
import { ConvictionSelect } from "./convictions/ConvictionsSelect.js";
import { getConvictions } from "./convictions/convictionsDataProvider.js";
import { NoteForm } from "./notes/NoteForm.js";
import { witnessListButton } from "./witnesses/WitnessListButton.js";
import { getWitnesses } from "./witnesses/witnessDataProvider.js";
import { noteListButton } from "./notes/NoteListButton.js";
import { OfficerSelect } from "./officers/OfficerSelect.js";
import { getOfficers } from "./officers/officerDataProvider.js";
import { filterListButton, FilterComponent } from "./criminals/Filter.js";
import { criminalListButton } from "./criminals/CriminalListButton.js";
import { DisplayNoteFormButton } from "./notes/NoteFormButton.js";
import "./witnesses/WitnessList.js";
import { dateInputFilter } from "./criminals/dateInputFilter.js";

DisplayNoteFormButton();
noteListButton();
witnessListButton();
criminalListButton();
dateInputFilter();
filterListButton();
NoteForm();
getWitnesses();
getCriminals().then(criminalList);
getConvictions().then(ConvictionSelect);
getOfficers().then(OfficerSelect);
FilterComponent();